<div class='achievements-awarded'></div>
<?php
    use AxalianAchievements\Entity\Achievement;

    $script = 'var achievementsUnlocked = [';

    /** @var Achievement $achievement */
    foreach($this->achievements as $i => $achievement){
        $script .= '"' . $achievement->getTitle() . '"';

        if($i != count($achievements) - 1){
            $script .= ',';
        }
    }

    $script .= ']';

    $this->inlineScript()->appendScript($script);