<?php
use AxalianAchievements\Entity\Achievement;

/** @var Achievement $achievement */

foreach($this->achievements as $achievement): ?><div class="achievement alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <span class="title"><?=$achievement->getTitle()?></span>
    <div class="description"><?=$achievement->getDescription()?></div>
</div><?php endforeach; ?>